name: Terraform 

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Module version
      id: tf_version
      run: |
        echo "::set-output name=TF_VERSION::$(awk '/required_version/{print $NF}' ./main.tf | tr -d \")"
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ steps.tf_version.outputs.TF_VERSION }}
    
    - name: Terraform Plan
      id: tf_plan
      run: |
        echo "::set-output name=TF_PLAN::$(terraform plan -out tfplan)"
  
    - name: Upload Terraform Plan to Artifact store
      id: tf_plan_upload
      uses: actions/upload-artifact@v2
      with:
        name: terraform_plan
        path: |
          ${{ steps.tf_plan.outputs.TF_PLAN }}
        
